name: Sync Publishing Secrets
on: [workflow_dispatch]
jobs:
  sync-secrets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^(MODRINTH|CURSEFORGE|MAVEN)_TOKEN$
          REPOSITORIES: |
            enjarai/do-a-barrel-roll
            enjarai/show-me-your-skin
            enjarai/recursive-resources
            enjarai/shared-resources
            enjarai/OmniHopper
            enjarai/moderate-loading-screen
            enjarai/client-paintings
          REPOSITORIES_LIST_REGEX: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
